### ISSUE TITLE
What data do we want to collect and how do we adjust the User Mutation for it

### ISSUE THREAD

**Issue by gould-ann** [samaritan-security/samaritan-backend#8]

**Comment by katebrune** [comment]
i think this stems from the functionality we want to have in the future:
- matching faces
- tracking
- temporary access
- multiple organizations
are some of the areas we'll have to think about when organizing the data and understand what we want to save.  

when binary recognition realizes we don't know someone, they should save them to the 'unknown' db. but if the same person is seen n times, we don't want to save n versions of them in the db, so we will need to be able to match faces. so we need to figure out (a) how to match faces and (b) what is the most ideal way to store what we need to compare faces

tracking relies on (a) camera information being well defined and (b) time. if X is seen at location Y at time Z, we can find all instances that include X and order them from time 0...n and we will see the route of their locations. for cameras, we should probably include physical location, IP, nickname. this would also force us to do something with facial recognition when we see someone, like adding this information to a db instead of just streaming the names to the frontend.

tempory access means that someone is 'known' so we should add them to the db of known people. mongo has a ttl we can set, so they will be deleted from 'known' or basically 'allowed' after that time. but we know who this person is and should utilize that information, so should probably move them to the 'unknown' db when they are no longer allowed, but keep the name with them. 

for multiple organizations we need to think about how we are organizhting information as a whole. are we (a) adding some 'organization' field and sorting out relevant data by this tag for each organization? or (b) setting up our application to run for one organization and setting up separate instances for each organization? downsides to (a) is that over time, we will acquire a lot of data and im not sure how realistic sorting it out by 'organization' will be

anyways, this is just my thoughts on some of this and some things we should think about before deciding how we want to structure data.

**Comment by gould-ann** [comment]
cool

**Comment by gould-ann** [comment]
is this a next tuesday problem @katebrune

**Comment by gould-ann** [comment]
I don't think this is a next tuesday problem but something to consider

**Comment by katebrune** [comment]
i think this is a next next tuesday problem @gould-ann

**Comment by gould-ann** [comment]
fffffffffffff
